name: macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: make
      run: cd Atif/src/cmake && make

    - uses: actions/upload-artifact@v3
      with:
        name: macOS
        path: ./Atif/src/cmake/AtifExe
